### ISSUE TITLE
Why did you add find user in resource collection code?

### ISSUE THREAD

**Issue by dougireton** [jtimberman/vagrant-cookbook#50]
@jtimberman I'm refactoring the code to find a user's home directory to add Windows support.

I see you specifically added support for looking up a user in the resource collection in the commits below. Can you explain the purpose of these additions? It seems like if the user and their home directory were created earlier during the Chef run, then they would already be available when `vagrant_plugin` needed them, or if new_resource.user is `nil` then it would never be found anyway.

I'm really wondering if we can cut out the support for finding the user in the Chef run `resource_collection`. It would make the code easier to maintain.

https://github.com/jtimberman/vagrant-cookbook/commit/d0180001876ec3b8150d8b5c4385e41cbd295e9a#diff-38a4aeddb4e620724d3b85362cb8b939R66

https://github.com/jtimberman/vagrant-cookbook/commit/d0180001876ec3b8150d8b5c4385e41cbd295e9a#diff-9dd581ae1baaef6ddac9d068f84b6639R65

**Comment by jtimberman** [comment]
This [commit](https://github.com/jtimberman/vagrant-cookbook/commit/342f809cb671715e5a277553bddb77e8879bd167) is where that was introduced. At the time the recipe is evaluated to build the resource collection, the user doesn't exist. This is because it happens during `load_current_resource`, [here](https://github.com/jtimberman/vagrant-cookbook/blob/292879b75355b9445725c17b1ffb5b52eb08d8cd/providers/plugin.rb#L26-L29).

**Comment by dougireton** [comment]
OK, makes sense.
